### ISSUE TITLE
jwt/login example CSRF ignored because of Bearer Token 

### ISSUE THREAD

**Issue by simasch** [spring-projects/spring-security-samples#116]
Hi, 

I tried the jwt/login example and noticed that the CSRF token is not generated when a Bearer token is present because of BearerTokenRequestMatcher.

The only request without Bearer token would be the auth request with basic authentication, but for this request CSRF is disabled.

Does the example make sense? Or why isn't CSRF disabled at all?

Thank you.

**Comment by marcusdacoregio** [comment]
Hi @simasch,

CSRF protection is unnecessary in this scenario because we are using stateless authentication. In other words, we are not dealing with Session Cookies, which are added to the request automatically by the browser, this way avoiding the majority of CSRF exploits. When using an `Authorization` header, we have to add the header manually using JavaScript.

The HTTP Basic authentication mechanism is also stateless, so no need for CSRF protection either.

**Comment by simasch** [comment]
Hi @marcusdacoregio 
That's what I thought :-)

Will https://github.com/spring-projects/spring-security-samples/blob/main/servlet/spring-boot/java/jwt/login/src/main/java/example/RestConfig.java be change accordingly?

**Comment by marcusdacoregio** [comment]
Hi @simasch,

What changes specifically do you expect to see in the configuration?

**Comment by simasch** [comment]
csrf(AbstractHttpConfigurer::disable)

instead of

    csrf((csrf) -> csrf.ignoringRequestMatchers("/token"))

Because it was very confusing that CSRF is configured but not used and now token was generated.

**Comment by simasch** [comment]
Makes sense!
Thank you
