### ISSUE TITLE
Can you provide a simple example of ajax login

### ISSUE THREAD

**Issue by HongJian-Yang** [spring-projects/spring-security-samples#137]
I have reviewed these examples and it seems that there are no examples of using Ajax login, such as

```
  @PostMapping("/login")
    public String login(String name, String pass) {
        // .. securityAuthentication code
        // ..
        return token;
    }
```
This may be very useful for projects with front-end and back-end separation

**Comment by marcusdacoregio** [comment]
Hi @HongJian-Yang, with `http.formLogin()` enabled, you can perform a POST to the same `/login` endpoint, it would look something like this:

```
curl -X POST http://localhost:8080/login
   -H "Content-Type: application/x-www-form-urlencoded" 
   -d "username=user&password=password" 
```

Remember that you might need a CSRF token.

Additionally, if you do not want the default login page, you can configure your `exceptionHandling()` to return a 401 instead of redirecting to `/login`.

```java
http
    .exceptionHandling(exceptions -> exceptions
        .authenticationEntryPoint(new HttpStatusEntryPoint(HttpStatus.UNAUTHORIZED));
    );
```
