### ISSUE TITLE
Add steps to generate credentials

### ISSUE THREAD

**Issue by AasthaSethia** [spring-projects/spring-security-samples#14]
How can I generate the files in credentials, the idp and rp ones? I want to try spring saml feature with another idp

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
