### ISSUE TITLE
Refresh token for JWT Login

### ISSUE THREAD

**Issue by huco95** [spring-projects/spring-security-samples#91]
It would be great to add how to implement refresh tokens for JWT Login sample. I can not find any good documentation or tutorial for this.

**Comment by marcusdacoregio** [comment]
Hi, @huco95.

I don't think the sample should have a way to mint refresh tokens as well since there is no standard way to do that. If you really need it you may consider creating a full-featured authorization server to deal with that, like Spring Authorization Server. See this issue https://github.com/spring-projects/spring-security/issues/9424
